{% set version = "0.8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-highr
  version: {{ version|replace("-", "_") }}

source:
  fn: highr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/highr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/highr/highr_{{ version }}.tar.gz
  sha256: 4bd01fba995f68c947a99bdf9aca15327a5320151e10bd0326fad50a6d8bc657

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('highr')"           # [not win]
    - "\"%R%\" -e \"library('highr')\""  # [win]

about:
  home: https://github.com/yihui/highr
  license: GPL
  summary: Provides syntax highlighting for R source code. Currently it supports LaTeX and HTML
    output. Source code of other languages is supported via Andre Simon's highlight
    package (<http://www.andre-simon.de>).
  license_family: GPL

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
